// +build !ignore_autogenerated

/*
Copyright 2019 The oVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// autogenerated by controller-gen object, do not modify manually

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderSpec) DeepCopyInto(out *OvirtClusterProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderSpec.
func (in *OvirtClusterProviderSpec) DeepCopy() *OvirtClusterProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtClusterProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderSpecList) DeepCopyInto(out *OvirtClusterProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvirtClusterProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderSpecList.
func (in *OvirtClusterProviderSpecList) DeepCopy() *OvirtClusterProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtClusterProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderSpecSpec) DeepCopyInto(out *OvirtClusterProviderSpecSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderSpecSpec.
func (in *OvirtClusterProviderSpecSpec) DeepCopy() *OvirtClusterProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderSpecStatus) DeepCopyInto(out *OvirtClusterProviderSpecStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderSpecStatus.
func (in *OvirtClusterProviderSpecStatus) DeepCopy() *OvirtClusterProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderStatus) DeepCopyInto(out *OvirtClusterProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderStatus.
func (in *OvirtClusterProviderStatus) DeepCopy() *OvirtClusterProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtClusterProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderStatusList) DeepCopyInto(out *OvirtClusterProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvirtClusterProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderStatusList.
func (in *OvirtClusterProviderStatusList) DeepCopy() *OvirtClusterProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtClusterProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderStatusSpec) DeepCopyInto(out *OvirtClusterProviderStatusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderStatusSpec.
func (in *OvirtClusterProviderStatusSpec) DeepCopy() *OvirtClusterProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtClusterProviderStatusStatus) DeepCopyInto(out *OvirtClusterProviderStatusStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtClusterProviderStatusStatus.
func (in *OvirtClusterProviderStatusStatus) DeepCopy() *OvirtClusterProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtClusterProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderSpec) DeepCopyInto(out *OvirtMachineProviderSpec) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderSpec.
func (in *OvirtMachineProviderSpec) DeepCopy() *OvirtMachineProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtMachineProviderSpec) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderSpecList) DeepCopyInto(out *OvirtMachineProviderSpecList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvirtMachineProviderSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderSpecList.
func (in *OvirtMachineProviderSpecList) DeepCopy() *OvirtMachineProviderSpecList {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderSpecList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtMachineProviderSpecList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderSpecSpec) DeepCopyInto(out *OvirtMachineProviderSpecSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderSpecSpec.
func (in *OvirtMachineProviderSpecSpec) DeepCopy() *OvirtMachineProviderSpecSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderSpecSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderSpecStatus) DeepCopyInto(out *OvirtMachineProviderSpecStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderSpecStatus.
func (in *OvirtMachineProviderSpecStatus) DeepCopy() *OvirtMachineProviderSpecStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderSpecStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderStatus) DeepCopyInto(out *OvirtMachineProviderStatus) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderStatus.
func (in *OvirtMachineProviderStatus) DeepCopy() *OvirtMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderStatusList) DeepCopyInto(out *OvirtMachineProviderStatusList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvirtMachineProviderStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderStatusList.
func (in *OvirtMachineProviderStatusList) DeepCopy() *OvirtMachineProviderStatusList {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderStatusList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtMachineProviderStatusList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderStatusSpec) DeepCopyInto(out *OvirtMachineProviderStatusSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderStatusSpec.
func (in *OvirtMachineProviderStatusSpec) DeepCopy() *OvirtMachineProviderStatusSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderStatusSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtMachineProviderStatusStatus) DeepCopyInto(out *OvirtMachineProviderStatusStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtMachineProviderStatusStatus.
func (in *OvirtMachineProviderStatusStatus) DeepCopy() *OvirtMachineProviderStatusStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtMachineProviderStatusStatus)
	in.DeepCopyInto(out)
	return out
}
